// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwhRE0dwSihooJT-c09aVHXCIpV6ueW64',
    appId: '1:200959807752:web:ca5c08f93a8d9a92191cbd',
    messagingSenderId: '200959807752',
    projectId: 'notes-app-2ac0d',
    authDomain: 'notes-app-2ac0d.firebaseapp.com',
    storageBucket: 'notes-app-2ac0d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8M6iI2kD33E2pW-93heHiw3gdXsd012s',
    appId: '1:200959807752:android:5965846f27daf931191cbd',
    messagingSenderId: '200959807752',
    projectId: 'notes-app-2ac0d',
    storageBucket: 'notes-app-2ac0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcPtaIpJzCr3sFEH0neaAYSoYqCHubT7I',
    appId: '1:200959807752:ios:da11e2cf9a56d9a6191cbd',
    messagingSenderId: '200959807752',
    projectId: 'notes-app-2ac0d',
    storageBucket: 'notes-app-2ac0d.appspot.com',
    iosClientId: '200959807752-e00v3fh9u6tkgndie50gu7d70m6at5u3.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleNotesApp',
  );
}
